### ISSUE TITLE
Discord.js v13 | Intents

### ISSUE THREAD

**Issue by Zaikonurami** [Saajith22/handler-djs#1]
https://github.com/Saajith22/handler-djs/blob/0f1e9f2cf6b28d261f815f12ad4200d4c87b38b4/index.js#L2

Replace it with
```js
const Discord = require('discord.js')
const { Intents } = require('discord.js')
```

https://github.com/Saajith22/handler-djs/blob/0f1e9f2cf6b28d261f815f12ad4200d4c87b38b4/index.js#L6#L10

Replace it with
```js
   intents: Intents.ALL
```

This is for better functionality

**Comment by SaajithDev** [comment]
Its v13 lmfao, `Intents.ALL` doesnt exist
